#%RAML 1.0
title: Interop Mock Central Directory
version: v1
baseUri: http://mock-central-directory/
mediaType: application/json
securitySchemes:
  basic:
    description: This API supports Basic Authentication.
    type: Basic Authentication
    
types: 
  
  Resource:
    type: object
    properties: 
      name: string
      providerUrl:
        type: string
        pattern: ^((http(s?))\:\/\/)?((([a-zA-Z0-9_\-]{2,}\.)+[a-zA-Z]{2,})|((?:(?:25[0-5]|2[0-4]\d|[01]\d\d|\d?\d)( ?(\.?\d)\.)){4}))(:[a-zA-Z0-9]+)?(\/[a-zA-Z0-9\-\._\?\,\'\/\\\+&amp;%\$#\=~]*)?$
      shortName: string
      preferred: string
      registered: string

  DFSP:
    type: object
    properties: 
      name: string
      shortName: string
      providerUrl: string
      schemeCode?: string
      dfspCode?: string
      key?: string
      secret?: string
    

  IdentifierType:
    type: object
    properties: 
      identifierType: string
      description: string
      
  Metadata:
    type: object
    properties: 
      directory: string
      urls: string
 
  Error:
    type: object
    properties: 
      error:
        type: ErrorDetail
    example:
      error: 
        id: UserNotFound
        message: End-User was not found
                
  ErrorDetail:
    type: object
    properties: 
      id: string
      message: string
      validationErrors?:
        type: array
        items: ValidationError

  ValidationError:
    type: object
    properties: 
      message: string
      params: 
        type: object
        properties: 
          key: string
          value?: string
          child?: string

/:
  get:
    description: Returns metadata associated with the directory
    securedBy: [null]
    responses: 
      200:
        body:
          type: Metadata


/health:
  displayName: HealthCheck resource
  description: This resource is included to provide a simple response to indicate that the API is up and running.
  get:
    responses: 
      200:
        body: 
          application/json: 
            properties:
              status: string
            example: |
              { 
                "status" : "ok" 
              }
          
/commands:
  /register:
    post:
      description: Register DFSP to use the central directory
      securedBy: [basic]
      body:
        type: DFSP
      responses: 
        201:
          body:
            type: DFSP

/identifier-types:
  get:
    description:  Get identifier types supported by the central directory
    securedBy: [basic]
    responses: 
      200:
        body:
          type: array
          items: IdentifierType
          
          
/resources:
  post:
    description: create a new identifier
    securedBy: [basic]
    body:
      properties:
        identifier: string
        preferred?: boolean
    responses:
      201:
        body:
          type: Resource
      404:
        body:
          type: Error
  get:
    description: Get resource information by supplying an identifier and identifier type
    securedBy: [basic]
    queryParameters:
      identifier:
        type: string
    responses:
      200:
        body:
          type: array
          items: 
            type: Resource
      404:
        body:
          type: Error

  